 FROM openjdk:11-jre-slim-buster
 MAINTAINER makul:fitness_app_db-module
 COPY target/fitness_app_db-module-0.0.1-SNAPSHOT.jar fitness_app_db-module-0.0.1-SNAPSHOT.jar
 CMD exec java -jar /fitness_app_db-module-0.0.1-SNAPSHOT.jar