server:
  port: 8122
  servlet:
    context-path: /fitnessweb-app
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    database: postgresql
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://databaseSecurity:5432/SecurityDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 3784